/**
 * User-facing UI strings. Use these keys in components instead of hardcoded text.
 */
export const UI_TEXT = {
  events: {
    upcoming: 'Предстоящие события',
    subtitle: 'Выберите ваше эксклюзивное событие',
    featured: 'Главное событие',
    thisMonth: 'В этом месяце',
  },
  nav: {
    events: 'СОБЫТИЯ',
    myTickets: 'МОИ БИЛЕТЫ',
    profile: 'ПРОФИЛЬ',
  },
  admin: {
    title: 'Центр управления',
    subtitle: 'Управление мероприятием',
    exit: 'Выход',
    reload: 'Обновить',
    bookings: 'Бронирования',
    venueLayout: 'План зала',
    selectEvent: 'Выберите событие',
    chooseEvent: '— Выберите событие —',
    createEvent: 'Создать событие',
    creatingEvent: 'Создаём…',
    refresh: 'Обновить',
    archiveEvent: 'Архивировать событие',
    publishEvent: 'Опубликовать событие',
    publishAgain: 'Опубликовать снова',
    archived: 'Архив',
    published: 'Опубликовано',
    draft: 'Черновик',
    statusLabel: 'Статус:',
    publishedCheckbox: 'Опубликовано',
    featuredCheckbox: 'Главное событие',
    loadingBookings: 'Загрузка бронирований…',
    loadingEvents: 'Загрузка событий…',
    noBookings: 'Бронирований пока нет.',
    noEvents: 'События не найдены.',
    emptyEventsList: 'Нет событий',
    eventUpdated: 'Событие обновлено.',
    eventPublished: 'Событие опубликовано.',
    eventArchived: 'Событие в архиве.',
    eventPublishedAgain: 'Событие снова опубликовано.',
    eventCreated: 'Событие создано.',
    resyncSeats: 'Пересчитать места',
    resyncSeatsSuccess: 'Места пересчитаны',
    resyncSeatsError: 'Ошибка пересчёта',
    deleteEvent: 'Удалить событие',
    deleteEventConfirmTitle: 'Удалить событие?',
    deleteEventConfirmText: 'Это действие нельзя отменить.',
    deleteEventActiveBookings: 'Есть активные бронирования.',
    deleteEventButton: 'Удалить',
  },
  event: {
    title: 'Название события',
    description: 'Описание',
    eventDate: 'Дата события',
    eventDatePlaceholder: 'ГГГГ-ММ-ДД',
    eventTime: 'Время события',
    eventTimePlaceholder: 'ЧЧ:ММ',
    venue: 'Площадка',
    venuePlaceholder: 'Название площадки или адрес',
    posterLabel: 'Афиша события',
    posterSectionLabel: 'Афиша мероприятия',
    posterPlaceholder: 'https://example.com/poster.jpg',
    ticketTemplateSectionLabel: 'Афиша билета (шаблон)',
    organizerPhone: 'Телефон организатора',
    contactOrganizer: 'Связаться с организатором',
    contactOrganizerTelegram: 'Задать вопрос организатору в Telegram',
    contactOrganizerPrompt: 'Есть вопросы по событию? Напишите организатору в Telegram.',
    contactOrganizerButton: 'Написать организатору',
    publishedWarning: 'Событие опубликовано и не может быть изменено.',
    titlePlaceholder: 'Название события',
    descriptionPlaceholder: 'Описание (необязательно)',
    phonePlaceholder: 'Телефон для оплаты',
    eventFallback: 'Событие',
    newEventTitle: 'Новое событие',
  },
  tables: {
    tables: 'Столы',
    table: 'Стол',
    seat: 'Место',
    addTable: 'Добавить стол',
    addTableHint: 'Нажмите на карту, чтобы разместить стол',
    tableAdded: 'Стол добавлен.',
    noTablesYet: 'Столов пока нет. Добавьте стол, чтобы расставить места.',
    seats: 'Места',
    available: 'Доступен к продаже',
    notAvailable: 'Недоступен',
    delete: 'Удалить стол',
    deleteConfirm: 'Удалить этот стол?',
    deleteWithBookingsTooltip: 'Нельзя удалить стол с бронированиями',
    tableDeleted: 'Стол удалён.',
    tableNumber: 'Номер стола',
    tableNumberInvalid: 'Номер стола должен быть целым положительным числом.',
    tableNumberDuplicate: 'Номера столов должны быть уникальными. Дубликат:',
    sizePercent: 'Размер (%)',
    shape: 'Форма',
    shapeCircle: 'Круг',
    shapeRect: 'Прямоугольник',
    widthPercent: 'Ширина (%)',
    heightPercent: 'Высота (%)',
    rotationDeg: 'Поворот (°)',
    widthPercentInvalid: 'Ширина должна быть больше 0.',
    heightPercentInvalid: 'Высота должна быть больше 0.',
    rotationInvalid: 'Поворот должен быть от -180 до 180.',
    tableColor: 'Цвет стола',
    tableCategory: 'Категория',
    tableCategoryVIP: 'VIP',
    tableCategoryPremium: 'Premium',
    tableCategoryStandard: 'Standard',
    visibleFrom: 'Показать с',
    visibleUntil: 'Показать до',
    visibleFromPlaceholder: 'ГГГГ-ММ-ДД или пусто',
    visibleUntilPlaceholder: 'ГГГГ-ММ-ДД или пусто',
    tableLabel: 'Стол {number} — {seats} мест',
    layoutImageUrl: 'Ссылка на изображение плана',
    layoutImagePlaceholder: 'https://example.com/layout.jpg',
    layoutImageHint: 'Изображение используется как фон плана зала.',
    layoutPreview: 'Предпросмотр плана',
    noLayoutImage: 'Ссылка на изображение не задана',
    layoutHint: 'Введите ссылку на изображение выше; предпросмотр обновится. Столы задаются в процентах (0–100).',
  },
  booking: {
    successTitle: 'Бронь создана',
    paymentPrompt: 'Для подтверждения брони переведите оплату организатору.\nПосле оплаты нажмите кнопку ниже.',
    paymentDetailsTitle: 'Реквизиты для оплаты:',
    paymentTransferTo: 'Переведите оплату на номер:',
    paymentPurpose: 'Назначение платежа: номер вашей брони',
    paymentNoPhoneFallback: 'Организатор свяжется с вами для оплаты.',
    paidButton: 'Я оплатил',
    backToEvents: 'Вернуться к событиям',
    seats: 'Места:',
    phone: 'Телефон:',
    status: 'Статус:',
    statusPaid: 'Оплачено',
    statusReserved: 'Зарезервировано',
    statusExpired: 'Истекло',
    statusPending: 'Ожидание',
    statusLabels: { paid: 'Оплачено', reserved: 'Зарезервировано', expired: 'Истекло', pending: 'Ожидание', awaiting_confirmation: 'Ожидает подтверждения', payment_submitted: 'Ожидает подтверждения', cancelled: 'Отменено' } as Record<string, string>,
    statusFilterAll: 'Все статусы',
    noBookingsForFilter: 'Нет бронирований с выбранным статусом.',
    awaitingConfirmationMessage: 'Ожидаем подтверждения оплаты администратором.',
    bookingId: 'ID брони:',
    telegramId: 'ID в Telegram:',
    expires: 'Истекает:',
    paymentConfirmed: 'Оплата подтверждена',
    confirmPayment: 'Подтвердить оплату',
    confirming: 'Подтверждаем…',
    expired: 'Истекло',
    anotherConfirmInProgress: 'Выполняется другое подтверждение',
  },
  seatMap: {
    seats: 'Места',
    available: 'доступно',
    reserved: 'зарезервировано',
    sold: 'продано',
    selected: 'выбрано',
    noLayoutImage: 'Изображение плана не задано',
    noTablesYet: 'Столов пока нет. Зайдите позже.',
    tableFree: 'Стол {number}, свободно {free}',
    notAvailableForSale: ', не доступен к продаже',
  },
  common: {
    save: 'Сохранить',
    saving: 'Сохраняем…',
    cancel: 'Отмена',
    unsavedChangesTitle: 'Несохранённые изменения',
    unsavedChangesText: 'Вы уверены, что хотите выйти без сохранения?',
    discardAndExit: 'Выйти без сохранения',
    saveAndExit: 'Сохранить и выйти',
    reset: 'Сбросить',
    refresh: 'Обновить',
    loading: 'Загрузка…',
    error: 'Ошибка',
    somethingWentWrong: 'Что-то пошло не так.',
    refreshPageAndRetry: 'Обновите страницу и попробуйте снова.',
    errors: {
      forbidden: 'Доступ запрещён. Войдите снова.',
      notFound: 'Не найдено. Обновите страницу.',
      expired: 'Бронирование истекло и не может быть подтверждено.',
      onlyReserved: 'Подтвердить можно только зарезервированные бронирования.',
      deleteTableWithBookings: 'Нельзя удалить стол: по нему есть бронирования',
      cannotDeactivateTableWithBookings: 'Нельзя удалить или скрыть стол, по которому есть активные брони.',
      default: 'Что-то пошло не так. Попробуйте снова.',
      unableToVerifyAccess: 'Не удалось проверить доступ. Откройте приложение из Telegram.',
      pleaseLogInToViewBookings: 'Войдите, чтобы увидеть свои бронирования.',
      couldNotLoadBookings: 'Не удалось загрузить бронирования. Попробуйте снова.',
      couldNotLoadEvent: 'Не удалось загрузить событие. Нажмите «Обновить».',
      loadEventsFailed: 'Не удалось загрузить события. Попробуйте ещё раз.',
    },
  },
  app: {
    back: 'Назад',
    refresh: 'Обновить',
    event: 'Событие',
    loadingLayout: 'Загрузка плана…',
    loadingEvent: 'Загрузка события…',
    loadingSeats: 'Загрузка мест…',
    returningToLayout: 'Возврат к плану…',
    freeSeats: 'Свободно мест:',
    tableNotAvailableForSale: 'Этот стол недоступен к продаже.',
    selectSeats: 'Выберите места',
    numberOfSeats: 'Количество мест',
    contactPhone: 'Контактный телефон',
    phonePlaceholder: '+7 999 000-00-00',
    commentLabel: 'Комментарий (ФИО)',
    commentPlaceholder: 'ФИО или комментарий',
    availabilityRefreshes: 'Данные обновляются автоматически.',
    addPhoneToContinue: 'Укажите телефон для продолжения.',
    selectAtLeastOneSeat: 'Выберите хотя бы одно место.',
    openInTelegramToBook: 'Откройте в Telegram для бронирования.',
    bookingSent: 'Бронирование отправлено. Проверьте Telegram.',
    continueBook: 'Продолжить / Забронировать',
    booking: 'Бронируем…',
    submitting: 'Отправка…',
    tableNotFound: 'Стол не найден. Вернитесь и выберите другой.',
    tableFullyBooked: 'Этот стол полностью занят. Вернитесь и выберите другой.',
    selectionAdjusted: 'Данные обновились. Ваш выбор был скорректирован.',
    myBookings: 'Мои бронирования',
    backToEvents: 'Вернуться к событиям',
    loadingBookings: 'Загрузка бронирований…',
    couldNotRefresh: 'Не удалось обновить данные. Нажмите «Обновить».',
    noBookingsYet: 'У вас пока нет бронирований. Вернитесь к событиям.',
    bookingNumber: 'Бронирование №',
    status: 'Статус:',
    expiresIn: 'Истекает через:',
    seats: 'Места:',
    total: 'Итого:',
    ticket: 'Билет',
    ticketsAfterPayment: 'Билеты появятся после подтверждения оплаты.',
    appTitle: 'Бронирование мест',
    admin: 'Админка',
    publishedEventsList: 'Список опубликованных событий',
    adminAccessActive: 'Админ-доступ активен.',
    openAdmin: 'Открыть админку',
    debugAdmin: 'Режим отладки',
    telegramUserId: 'ID в Telegram:',
    isAdminLabel: 'Админ:',
    roleLoginLabel: 'Роль (вход):',
    roleTokenLabel: 'Роль (токен):',
    telegramWebAppNotFound: 'Telegram WebApp не обнаружен. Локальный режим.',
    telegramInitDataReceived: 'Telegram initData получен.',
    authTelegram: 'Авторизация Telegram…',
    user: 'Пользователь:',
    loadingEvents: 'Загружаем события…',
    events: 'События',
    noPublishedEvents: 'Пока нет опубликованных событий. Попробуйте снова позже.',
    noTitle: 'Без названия',
    selectedSeatCount: 'Количество выбранных мест',
  },
} as const;

export type UI_TEXT = typeof UI_TEXT;
