-- Schema of the tickets database, read from the live Supabase project
-- (wusmsvtciztfkynaufko) catalog on 2026-10-03. Public schema only: the
-- `storage` schema is created by the Storage API itself.
--
-- Load into an EMPTY database:
--   docker compose exec -T db psql -U postgres -d tickets -v ON_ERROR_STOP=1 < schema.sql
SET search_path = public;

CREATE TABLE public.admins (id bigint NOT NULL, created_at timestamp with time zone DEFAULT now());
CREATE TABLE public.app_users (id bigint NOT NULL, platform text DEFAULT 'telegram'::text NOT NULL, first_name text, last_name text, username text, last_seen timestamp with time zone DEFAULT now(), privacy_consented_at timestamp with time zone, email text, email_set_at timestamp with time zone);
CREATE TABLE public.bookings (id text NOT NULL, event_id text NOT NULL, table_id text, user_telegram_id bigint, user_phone text, seat_indices integer[], seats_booked integer, status text NOT NULL, created_at timestamp with time zone DEFAULT now(), expires_at timestamp with time zone, user_comment text, total_amount numeric NOT NULL, ticket_file_url text, is_used boolean DEFAULT false, platform text DEFAULT 'telegram'::text, user_vk_id bigint);
CREATE TABLE public.controllers (id bigint NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, platform text DEFAULT 'telegram'::text NOT NULL, label text);
CREATE TABLE public.event_tables (id text NOT NULL, event_id text NOT NULL, number integer NOT NULL, seats_total integer NOT NULL, seats_available integer NOT NULL, x integer, y integer, center_x numeric, center_y numeric, size_percent numeric, shape text DEFAULT 'circle'::text NOT NULL, color text, created_at timestamp with time zone DEFAULT now(), is_available boolean DEFAULT false, is_active boolean DEFAULT true, visible_from timestamp with time zone, visible_until timestamp with time zone, width_percent numeric, height_percent numeric, rotation_deg numeric DEFAULT 0, ticket_category_id text, object_type text DEFAULT 'table'::text NOT NULL, label text, label_font_size integer, limited_view boolean DEFAULT false NOT NULL);
CREATE TABLE public.events (id text NOT NULL, title text NOT NULL, description text, date timestamp with time zone, image_url text, layout_image_url text, organizer_phone text, published boolean DEFAULT false, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), tables jsonb, event_date date, event_time time without time zone, venue text, layout_image_path text, layout_image_version integer DEFAULT 1, ticket_categories jsonb, poster_image_path text, poster_image_version integer DEFAULT 1, ticket_template_url text, is_featured boolean DEFAULT false, timezone_offset_minutes integer DEFAULT 180, organizer_id bigint, layout_width integer, layout_height integer, archived boolean DEFAULT false NOT NULL, payment_methods text[] DEFAULT '{transfer}'::text[] NOT NULL);
CREATE TABLE public.layout_changes (id uuid DEFAULT gen_random_uuid() NOT NULL, event_id text NOT NULL, table_id text NOT NULL, action text NOT NULL, previous_data jsonb, new_data jsonb, admin_id bigint, created_at timestamp with time zone DEFAULT now());
CREATE TABLE public.organizers (user_id bigint NOT NULL, event_id text NOT NULL, platform text DEFAULT 'telegram'::text NOT NULL, label text, created_at timestamp with time zone DEFAULT now());
CREATE TABLE public.payments (id uuid DEFAULT gen_random_uuid() NOT NULL, booking_id text NOT NULL, inv_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider text DEFAULT 'robokassa'::text NOT NULL, amount numeric(12,2) NOT NULL, status text DEFAULT 'pending'::text NOT NULL, is_test boolean DEFAULT false NOT NULL, op_key text, payment_method text, fee numeric(12,2), email text, created_at timestamp with time zone DEFAULT now() NOT NULL, paid_at timestamp with time zone, raw jsonb, op_state_code integer, op_state_at timestamp with time zone, op_state_raw text, refund_request_id text, refund_state text, refund_requested_at timestamp with time zone, refunded_at timestamp with time zone, refund_requested_by text);
CREATE TABLE public.team_invites (token text NOT NULL, role text NOT NULL, event_id text, label text, created_by bigint, created_at timestamp with time zone DEFAULT now() NOT NULL, expires_at timestamp with time zone NOT NULL, used_at timestamp with time zone, used_by bigint);
CREATE TABLE public.venues (id uuid NOT NULL, name text NOT NULL, layout_image_url text, layout_image_path text, layout_width integer, layout_height integer, objects jsonb DEFAULT '[]'::jsonb NOT NULL, ticket_categories jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);

ALTER TABLE admins ADD CONSTRAINT admins_pkey PRIMARY KEY (id);
ALTER TABLE app_users ADD CONSTRAINT app_users_pkey PRIMARY KEY (id, platform);
ALTER TABLE bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE controllers ADD CONSTRAINT controllers_pkey PRIMARY KEY (id);
ALTER TABLE event_tables ADD CONSTRAINT event_tables_pkey PRIMARY KEY (id);
ALTER TABLE event_tables ADD CONSTRAINT event_tables_shape_check CHECK ((shape = ANY (ARRAY['circle'::text, 'rect'::text])));
ALTER TABLE events ADD CONSTRAINT events_payment_methods_check CHECK (((array_length(payment_methods, 1) >= 1) AND (payment_methods <@ ARRAY['robokassa'::text, 'transfer'::text])));
ALTER TABLE events ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE layout_changes ADD CONSTRAINT layout_changes_pkey PRIMARY KEY (id);
ALTER TABLE organizers ADD CONSTRAINT organizers_pkey PRIMARY KEY (user_id, event_id, platform);
ALTER TABLE payments ADD CONSTRAINT payments_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE payments ADD CONSTRAINT payments_inv_id_key UNIQUE (inv_id);
ALTER TABLE payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE team_invites ADD CONSTRAINT organizer_needs_event CHECK (((role <> 'organizer'::text) OR (event_id IS NOT NULL)));
ALTER TABLE team_invites ADD CONSTRAINT team_invites_pkey PRIMARY KEY (token);
ALTER TABLE team_invites ADD CONSTRAINT team_invites_role_check CHECK ((role = ANY (ARRAY['controller'::text, 'organizer'::text])));
ALTER TABLE venues ADD CONSTRAINT venues_pkey PRIMARY KEY (id);

CREATE INDEX idx_bookings_event_id ON public.bookings USING btree (event_id);
CREATE INDEX idx_bookings_event_status ON public.bookings USING btree (event_id, status);
CREATE INDEX idx_bookings_status ON public.bookings USING btree (status);
CREATE INDEX idx_bookings_table_id ON public.bookings USING btree (table_id);
CREATE INDEX idx_bookings_user_telegram_id ON public.bookings USING btree (user_telegram_id) WHERE (user_telegram_id IS NOT NULL);
CREATE INDEX idx_bookings_user_vk_id ON public.bookings USING btree (user_vk_id) WHERE (user_vk_id IS NOT NULL);
CREATE INDEX idx_event_tables_event_id ON public.event_tables USING btree (event_id);
CREATE INDEX idx_event_tables_ticket_category ON public.event_tables USING btree (ticket_category_id);
CREATE UNIQUE INDEX unique_event_table_number_active ON public.event_tables USING btree (event_id, number) WHERE ((is_active = true) AND (object_type = 'table'::text));
CREATE INDEX idx_layout_changes_event_id ON public.layout_changes USING btree (event_id);
CREATE INDEX idx_layout_changes_table_id ON public.layout_changes USING btree (table_id);
CREATE INDEX payments_booking_id_idx ON public.payments USING btree (booking_id);
CREATE INDEX payments_refund_pending_idx ON public.payments USING btree (refund_state) WHERE (refund_state = 'processing'::text);
CREATE INDEX payments_status_idx ON public.payments USING btree (status);
CREATE INDEX venues_name_idx ON public.venues USING btree (name);

ALTER TABLE bookings ADD CONSTRAINT bookings_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;
ALTER TABLE bookings ADD CONSTRAINT bookings_table_id_fkey FOREIGN KEY (table_id) REFERENCES event_tables(id);
ALTER TABLE event_tables ADD CONSTRAINT event_tables_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;
ALTER TABLE payments ADD CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE;
ALTER TABLE team_invites ADD CONSTRAINT team_invites_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;

ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.controllers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.layout_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view tables" ON public.event_tables AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Public can view events" ON public.events AS PERMISSIVE FOR SELECT TO public USING (true);

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.admins TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.app_users TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.bookings TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.controllers TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.event_tables TO service_role;
GRANT SELECT ON public.event_tables TO anon;
GRANT SELECT ON public.event_tables TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.events TO service_role;
GRANT SELECT ON public.events TO anon;
GRANT SELECT ON public.events TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.layout_changes TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.organizers TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payments TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payments TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payments TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.team_invites TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.team_invites TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.team_invites TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.venues TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.venues TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.venues TO service_role;

-- supabase-js inserts into payments rely on the identity sequence.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
